<?php

use Illuminate\Database\Seeder;

class EmployeesTableSeeder extends Seeder {

    public function run() {
        DB::table('employees')->insert(
                [
                    // ========================================================
                    // FTE employees
                    // ========================================================
                    [
                        'employeeId' => "CL0004",
                        'firstName' => null,
                        'lastName' => null,
                        'fullName' => "Santosh Kumar",
                        'avatar' => "../../img/caratlane/avatar-150.png",
                        'location' => null,
                        'email' => null,
                        'phone' => null,
                        'productivity' => 8.0,
                        'employementType' => "FTE",
                        // 'morning_shift' => 0,
                        'isTeamLeader' => 0,
                        'isProjectManager' => 1
                    ],
                    [
                        'employeeId' => "CL0138",
                        'firstName' => null,
                        'lastName' => null,
                        'fullName' => "Appolin A",
                        'avatar' => "../../img/caratlane/avatar-150.png",
                        'location' => null,
                        'email' => null,
                        'phone' => null,
                        'productivity' => 8.0,
                        'employementType' => "FTE",
                        // 'morning_shift' => 0,
                        'isTeamLeader' => 1,
                        'isProjectManager' => 0
                    ],
                    [
                        'employeeId' => "CL0014",
                        'firstName' => null,
                        'lastName' => null,
                        'fullName' => "Prasanna T",
                        'avatar' => "../../img/caratlane/avatar-150.png",
                        'location' => null,
                        'email' => null,
                        'phone' => null,
                        'productivity' => 8.0,
                        'employementType' => "FTE",
                        // 'morning_shift' => 0,
                        'isTeamLeader' => 1,
                        'isProjectManager' => 0
                    ],
                    [
                        'employeeId' => "CL0154",
                        'firstName' => null,
                        'lastName' => null,
                        'fullName' => "Venkatesan R",
                        'avatar' => "../../img/caratlane/avatar-150.png",
                        'location' => null,
                        'email' => null,
                        'phone' => null,
                        'productivity' => 8.0,
                        'employementType' => "FTE",
                        // 'morning_shift' => 0,
                        'isTeamLeader' => 0,
                        'isProjectManager' => 0
                    ],
                    [
                        'employeeId' => "CL0171",
                        'firstName' => null,
                        'lastName' => null,
                        'fullName' => "Manoj Kumar",
                        'avatar' => "../../img/caratlane/avatar-150.png",
                        'location' => null,
                        'email' => null,
                        'phone' => null,
                        'productivity' => 8.0,
                        'employementType' => "FTE",
                        // 'morning_shift' => 0,
                        'isTeamLeader' => 0,
                        'isProjectManager' => 0
                    ],
                    [
                        'employeeId' => "CL0216",
                        'firstName' => null,
                        'lastName' => null,
                        'fullName' => "Gokul Anand Raj",
                        'avatar' => "../../img/caratlane/avatar-150.png",
                        'location' => null,
                        'email' => null,
                        'phone' => null,
                        'productivity' => 8.0,
                        'employementType' => "FTE",
                        // 'morning_shift' => 0,
                        'isTeamLeader' => 0,
                        'isProjectManager' => 0
                    ],
                    [
                        'employeeId' => "CL0223",
                        'firstName' => null,
                        'lastName' => null,
                        'fullName' => "Mukesh Raj",
                        'avatar' => "../../img/caratlane/avatar-150.png",
                        'location' => null,
                        'email' => null,
                        'phone' => null,
                        'productivity' => 8.0,
                        'employementType' => "FTE",
                        // 'morning_shift' => 0,
                        'isTeamLeader' => 0,
                        'isProjectManager' => 0
                    ], [
                        'employeeId' => "CL0286",
                        'firstName' => null,
                        'lastName' => null,
                        'fullName' => "Linto Joy",
                        'avatar' => "../../img/caratlane/avatar-150.png",
                        'location' => null,
                        'email' => null,
                        'phone' => null,
                        'productivity' => 8.0,
                        'employementType' => "FTE",
                        // 'morning_shift' => 0,
                        'isTeamLeader' => 0,
                        'isProjectManager' => 0
                    ],
                    [
                        'employeeId' => "CL0284",
                        'firstName' => null,
                        'lastName' => null,
                        'fullName' => "Muhammed Sabique",
                        'avatar' => "../../img/caratlane/avatar-150.png",
                        'location' => null,
                        'email' => null,
                        'phone' => null,
                        'productivity' => 8.0,
                        'employementType' => "FTE",
                        // 'morning_shift' => 0,
                        'isTeamLeader' => 0,
                        'isProjectManager' => 0
                    ], [
                        'employeeId' => "CL0285",
                        'firstName' => null,
                        'lastName' => null,
                        'fullName' => "Arun J",
                        'avatar' => "../../img/caratlane/avatar-150.png",
                        'location' => null,
                        'email' => null,
                        'phone' => null,
                        'productivity' => 8.0,
                        'employementType' => "FTE",
                        // 'morning_shift' => 0,
                        'isTeamLeader' => 0,
                        'isProjectManager' => 0
                    ],
                    // ========================================================
                    // intern employees
                    // ========================================================
                    [
                        'employeeId' => "CLI070",
                        'firstName' => null,
                        'lastName' => null,
                        'fullName' => "Selva Kumar S",
                        'avatar' => "../../img/caratlane/avatar-150.png",
                        'location' => null,
                        'email' => null,
                        'phone' => null,
                        'productivity' => 4.0,
                        'employementType' => "Intern",
                        // 'morning_shift' => 1,
                        'isTeamLeader' => 0,
                        'isProjectManager' => 0
                    ],
                    [
                        'employeeId' => "CLI076",
                        'firstName' => null,
                        'lastName' => null,
                        'fullName' => "Venkatesh R",
                        'avatar' => "../../img/caratlane/avatar-150.png",
                        'location' => null,
                        'email' => null,
                        'phone' => null,
                        'productivity' => 4.0,
                        'employementType' => "Intern",
                        // 'morning_shift' => 0,
                        'isTeamLeader' => 0,
                        'isProjectManager' => 0
                    ],
                    [
                        'employeeId' => "CLI082",
                        'firstName' => null,
                        'lastName' => null,
                        'fullName' => "Nagarajan GS",
                        'avatar' => "../../img/caratlane/avatar-150.png",
                        'location' => null,
                        'email' => null,
                        'phone' => null,
                        'productivity' => 4.0,
                        'employementType' => "Intern",
                        // 'morning_shift' => 1,
                        'isTeamLeader' => 0,
                        'isProjectManager' => 0
                    ],
                    [
                        'employeeId' => "CLI074",
                        'firstName' => null,
                        'lastName' => null,
                        'fullName' => "Balamurugan",
                        'avatar' => "../../img/caratlane/avatar-150.png",
                        'location' => null,
                        'email' => null,
                        'phone' => null,
                        'productivity' => 4.0,
                        'employementType' => "Intern",
                        // 'morning_shift' => 0,
                        'isTeamLeader' => 0,
                        'isProjectManager' => 0
                    ],
                    [
                        'employeeId' => "CLI075",
                        'firstName' => null,
                        'lastName' => null,
                        'fullName' => "Prince Jeyaseelan",
                        'avatar' => "../../img/caratlane/avatar-150.png",
                        'location' => null,
                        'email' => null,
                        'phone' => null,
                        'productivity' => 4.0,
                        'employementType' => "Intern",
                        // 'morning_shift' => 1,
                        'isTeamLeader' => 0,
                        'isProjectManager' => 0
                    ],
                    [
                        'employeeId' => "CLI077",
                        'firstName' => null,
                        'lastName' => null,
                        'fullName' => "Prabhu K",
                        'avatar' => "../../img/caratlane/avatar-150.png",
                        'location' => null,
                        'email' => null,
                        'phone' => null,
                        'productivity' => 4.0,
                        'employementType' => "Intern",
                        // 'morning_shift' => 0,
                        'isTeamLeader' => 0,
                        'isProjectManager' => 0
                    ],
                    [
                        'employeeId' => "CLI078",
                        'firstName' => null,
                        'lastName' => null,
                        'fullName' => "Saisudarsn V",
                        'avatar' => "../../img/caratlane/avatar-150.png",
                        'location' => null,
                        'email' => null,
                        'phone' => null,
                        'productivity' => 4.0,
                        'employementType' => "Intern",
                        // 'morning_shift' => 1,
                        'isTeamLeader' => 0,
                        'isProjectManager' => 0
                    ],
                    [
                        'employeeId' => "CLI079",
                        'firstName' => null,
                        'lastName' => null,
                        'fullName' => "Sathishkumar S",
                        'avatar' => "../../img/caratlane/avatar-150.png",
                        'location' => null,
                        'email' => null,
                        'phone' => null,
                        'productivity' => 4.0,
                        'employementType' => "Intern",
                        // 'morning_shift' => 0,
                        'isTeamLeader' => 0,
                        'isProjectManager' => 0
                    ],
                    [
                        'employeeId' => "CLI080",
                        'firstName' => null,
                        'lastName' => null,
                        'fullName' => "Richard Benny G",
                        'avatar' => "../../img/caratlane/avatar-150.png",
                        'location' => null,
                        'email' => null,
                        'phone' => null,
                        'productivity' => 4.0,
                        'employementType' => "Intern",
                        // 'morning_shift' => 1,
                        'isTeamLeader' => 0,
                        'isProjectManager' => 0
                    ],
                    [
                        'employeeId' => "CLI081",
                        'firstName' => null,
                        'lastName' => null,
                        'fullName' => "Vinothkumar J",
                        'avatar' => "../../img/caratlane/avatar-150.png",
                        'location' => null,
                        'email' => null,
                        'phone' => null,
                        'productivity' => 4.0,
                        'employementType' => "Intern",
                        // 'morning_shift' => 0,
                        'isTeamLeader' => 0,
                        'isProjectManager' => 0
                    ],
                    [
                        'employeeId' => "CLI083",
                        'firstName' => null,
                        'lastName' => null,
                        'fullName' => "Abin Babu E",
                        'avatar' => "../../img/caratlane/avatar-150.png",
                        'location' => null,
                        'email' => null,
                        'phone' => null,
                        'productivity' => 4.0,
                        'employementType' => "Intern",
                        // 'morning_shift' => 1,
                        'isTeamLeader' => 0,
                        'isProjectManager' => 0
                    ],
                    [
                        'employeeId' => "CLI084",
                        'firstName' => null,
                        'lastName' => null,
                        'fullName' => "Elavarasan S",
                        'avatar' => "../../img/caratlane/avatar-150.png",
                        'location' => null,
                        'email' => null,
                        'phone' => null,
                        'productivity' => 4.0,
                        'employementType' => "Intern",
                        // 'morning_shift' => 0,
                        'isTeamLeader' => 0,
                        'isProjectManager' => 0
                    ],
                    [
                        'employeeId' => "CLI085",
                        'firstName' => null,
                        'lastName' => null,
                        'fullName' => "Gowtham D",
                        'avatar' => "../../img/caratlane/avatar-150.png",
                        'location' => null,
                        'email' => null,
                        'phone' => null,
                        'productivity' => 4.0,
                        'employementType' => "Intern",
                        // 'morning_shift' => 1,
                        'isTeamLeader' => 0,
                        'isProjectManager' => 0
                    ],
                    [
                        'employeeId' => "CLI086",
                        'firstName' => null,
                        'lastName' => null,
                        'fullName' => "Karthik C",
                        'avatar' => "../../img/caratlane/avatar-150.png",
                        'location' => null,
                        'email' => null,
                        'phone' => null,
                        'productivity' => 4.0,
                        'employementType' => "Intern",
                        // 'morning_shift' => 0,
                        'isTeamLeader' => 0,
                        'isProjectManager' => 0
                    ],
                    [
                        'employeeId' => "CLI087",
                        'firstName' => null,
                        'lastName' => null,
                        'fullName' => "Maheshwaran M",
                        'avatar' => "../../img/caratlane/avatar-150.png",
                        'location' => null,
                        'email' => null,
                        'phone' => null,
                        'productivity' => 4.0,
                        'employementType' => "Intern",
                        // 'morning_shift' => 1,
                        'isTeamLeader' => 0,
                        'isProjectManager' => 0
                    ],
                    [
                        'employeeId' => "CLI088",
                        'firstName' => null,
                        'lastName' => null,
                        'fullName' => "Suresh L",
                        'avatar' => "../../img/caratlane/avatar-150.png",
                        'location' => null,
                        'email' => null,
                        'phone' => null,
                        'productivity' => 4.0,
                        'employementType' => "Intern",
                        // 'morning_shift' => 0,
                        'isTeamLeader' => 0,
                        'isProjectManager' => 0
                    ], [
                        'employeeId' => "CLI089",
                        'firstName' => null,
                        'lastName' => null,
                        'fullName' => "Suriya Kumar.K",
                        'avatar' => "../../img/caratlane/avatar-150.png",
                        'location' => null,
                        'email' => null,
                        'phone' => null,
                        'productivity' => 4.0,
                        'employementType' => "Intern",
                        // 'morning_shift' => 1,
                        'isTeamLeader' => 0,
                        'isProjectManager' => 0
                    ],
                    [
                        'employeeId' => "CLI090",
                        'firstName' => null,
                        'lastName' => null,
                        'fullName' => "Shanmuga M",
                        'avatar' => "../../img/caratlane/avatar-150.png",
                        'location' => null,
                        'email' => null,
                        'phone' => null,
                        'productivity' => 4.0,
                        'employementType' => "Intern",
                        // 'morning_shift' => 0,
                        'isTeamLeader' => 0,
                        'isProjectManager' => 0
                    ]
                ]
        );
    }

}
